parameters:
#    seiffert_infrastructurer_web.example.class: Seiffert\InfrastructurerWebBundle\Example

services:
#    seiffert_infrastructurer_web.example:
#        class: %seiffert_infrastructurer_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
